# Generated by Django 3.0.7 on 2020-08-02 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectManagement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='docFile',
            field=models.FileField(default=None, upload_to='documents/%Y/%m/%d'),
        ),
    ]
