# Generated by Django 3.0.7 on 2020-06-20 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectManagement', '0002_auto_20200620_0736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='code_project',
            field=models.CharField(default='pr-: 2020-06-20 06:36:57.532605+00:00', max_length=200, primary_key=True, serialize=False),
        ),
    ]
