# Generated by Django 3.0.7 on 2020-08-02 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectManagement', '0002_document_docfile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='path',
        ),
    ]
