# Generated by Django 3.0.7 on 2020-08-02 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectManagement', '0003_remove_document_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='docFile',
            field=models.FileField(blank=True, default=None, upload_to='documents/%Y/%m/%d'),
        ),
    ]
