# Generated by Django 3.0.7 on 2020-08-02 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectManagement', '0004_auto_20200802_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='docFile',
            field=models.FileField(default=None, upload_to='documents/%Y/%m/%d'),
        ),
    ]
