# Generated by Django 3.0.7 on 2020-06-20 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectManagement', '0005_auto_20200620_0737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='code_project',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
