export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAILED";
export const USER_LOADING = "USER_LOADING";
export const USER_LOADED = "USER_LOADED";
export const GET_ERRORS = "GET_ERRORS";
export const CREATE_MESSAGE = "CREATE_MESSAGE";
export const AUTH_ERROR = "AUTH_ERROR";


export const STARRED_REQUEST_PROJECTS = "STARRED_REQUEST_PROJECTS";
export const STARRED_SUCCESS_PROJECTS = "STARRED_SUCCESS_PROJECTS";
export const STARRED_FAILURE_PROJECTS = "STARRED_FAILURE_PROJECTS";


